### ISSUE TITLE
Not working please help

### ISSUE THREAD

**Issue by ExpertMaker** [beeper/mac-registration-provider#10]
Hello! I made a VM using VMWare for both Mac OS Sonoma and Big Sur, but both display the same error. I download the file and run the commands in terminal but I always get
2023/12/28 06:53:26 Starting mac-registration-provider 173b05fd
2023/12/28 06:53:26 Loading identityservicesd
2023/12/28 06:53:26 No offsets found for 11.0.1/20B29/amd64 (hash: 1a9cc9305e1621a2024a0f2c70fe77af0d0cf1fbd7e971ecd443f2fd587b12fc)

What should I do?
Thanks!

**Comment by NathanKassab** [comment]
Virtual machines don't work for this process, as far as I know. You may need to get a real mac computer.

**Comment by 0xdevalias** [comment]
The specific error here is because `11.0.1` isn't a currently supported version:

- https://github.com/beeper/mac-registration-provider#supported-macos-versions
- https://github.com/beeper/mac-registration-provider/blob/main/nac/offsets.go

@ExpertMaker If you're able to follow the instructions in [this comment](https://github.com/beeper/mac-registration-provider/issues/9#issuecomment-1872393053) and upload the binary somewhere, someone might be able to reverse it to get the correct offsets and add support.

**Comment by asherdundas** [comment]
I just tried with a working version of macos, but I still get the same error. What should I do?

**Comment by 0xdevalias** [comment]
@asherdundas Can you paste the full error here? That will tell us the specific macOS version you're running, and the `sha256sum` of the `/System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd` binary; which is required to understand exactly why you're getting the error.

At a guess though, I would say that you're potentially not using a supported version like you think you are.

**Comment by 0xdevalias** [comment]
@melvinjcuretonjr What would have been more helpful here is if @tulir explicitly said that support for that version was just merged in https://github.com/beeper/mac-registration-provider/pull/28 , and so if you use the latest version it should work.
